/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    id("test.project.build.java-library-conventions")
}

dependencies {
    api(project(":list"))
}
